const stringConstants = {
  noUsername: "Username is required",
  noEmail: "Email is required",
  noPassword: "Password is required",
  usernameExsist: "Username already exsist, try with new username",
  emailExsist: "Email already exsist, try different email",
  noUser: "You have not registered to our product, signup before login",
  incorrectPassword: "Incorrect password, Try again",
  noProjectSelected: "Select a project first to add dataEntry",
  noName: "Name is required",
  noDescription: "Description is required",
  noLocation: "Location is required",
  noDate: "Date is required",
  noMilestones: "Project Milestones is required",
  nameExsist: "This name already exsist, choose other",
  noProject: "Project not found",
  updateExsist: "Today's update already exists, reupdate for further changes",
  noSocietyName: "Please provide society name",
  societyExists: "society name already exsist, try different name",
  societyNotFound: "There is no such society, Please provide correct Id",
  serverError: "Internal server error",
  noFamily: "No Family is found with this id",
  activityNotFound: "No Activity found with this id",
};

module.exports = stringConstants;
