import Head from "next/head";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { persistor, store } from "@/app/store";
// import "styles/globals.scss";
// import "styles/main.css";
import "@/app/globals.css";
// import { ApolloProvider } from "@apollo/client";
import AppLayout from "../components/AppLayout";
// import client from "@/app/services/auth-service-client";
import { useRouter } from "next/router";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

function MyApp({ Component, pageProps }) {
  const { pathname } = useRouter();
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor}>
        <Head>
          <title>SkillForge</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/assets/favicon.ico" />
        </Head>
        {pathname.includes("/login") ? (
          <Component {...pageProps} />
        ) : (
          <>
            <AppLayout>
              <Component {...pageProps} />
            </AppLayout>
            <ToastContainer
              position="top-right"
              autoClose={5000}
              hideProgressBar
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="colored"
            />
          </>
        )}
      </PersistGate>
    </Provider>
  );
}

export default MyApp;
