export const CREATE_ASSESSMENT = "CREATE_ASSESSMENT";
export const CREATE_ASSESSMENT_SUCCESS = "CREATE_ASSESSMENT_SUCCESS";
export const CREATE_ASSESSMENT_FAILURE = "CREATE_ASSESSMENT_FAILURE";
export const CREATE_ASSESSMENT_INIT = "CREATE_ASSESSMENT_INIT";
