export const CREATE_USER_ASSESSMENT = "CREATE_USER_ASSESSMENT";
export const CREATE_USER_ASSESSMENT_SUCCESS = "CREATE_USER_ASSESSMENT_SUCCESS";
export const CREATE_USER_ASSESSMENT_FAILURE = "CREATE_USER_ASSESSMENT_FAILURE";
export const CREATE_USER_ASSESSMENT_INIT = "CREATE_USER_ASSESSMENT_INIT";

export const GET_NEXT_QUESTION = "GET_NEXT_QUESTION";
export const GET_NEXT_QUESTION_SUCCESS = "GET_NEXT_QUESTION_SUCCESS";
export const GET_NEXT_QUESTION_FAILURE = "GET_NEXT_QUESTION_FAILURE";
export const GET_NEXT_QUESTION_INIT = "GET_NEXT_QUESTION_INIT";
